[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "icsmtl"
version = "0.1.0"
description = "A collection of scrapers that convert common web sources into .ics files"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4",
    "gql[requests]",
    "lxml",
    "pyxdg",
    "requests",
    "transformers",
    "flash-linear-attention", # or just fla-core? https://github.com/fla-org/flash-linear-attention?tab=readme-ov-file#installation
    "pillow[webp,jpeg2000]",
]

[project.scripts]
catics = "icsmtl.catics:main"
cultmtl = "icsmtl.cultmtl:main"
meetup = "icsmtl.meetup:main"
mtlrave-telegram = "icsmtl.mtlrave_telegram:main"
