[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "icsmtl"
version = "0.1.0"
description = "A collection of scrapers that convert common web sources into .ics files"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "gql[requests]>=4.0.0",
    "lxml>=6.0.2",
    "pyxdg>=0.28",
    "requests>=2.32.5",
]

[project.scripts]
catics = "icsmtl.catics:main"
ics-ocr-flyer = "icsmtl.flyer:main"
cultmtl = "icsmtl.cultmtl:main"
meetup = "icsmtl.meetup:main"
mtlrave-telegram = "icsmtl.mtlrave_telegram:main"
